FROM selenium/standalone-chrome:latest

USER root

# Установка системных пакетов (если нужно)
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-dev \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-setuptools \
    && apt-get clean

# Установка зависимостей Python
COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip && pip install -r /app/requirements.txt

# Копируем скрипты
COPY Parser_Yand_segm_v6.py /app/Parser_Yand_segm_v6.py
COPY Web_scraper_Avito.py /app/Web_scraper_Avito.py

WORKDIR /app

# По умолчанию запускаем Avito парсер (можно переопределить в docker-compose)
CMD ["python3", "Web_scraper_Avito.py"]